# Mouse movement bindings
bind = SUPER ALT, Left,  exec, ydotool mousemove -x -20 -y 0
bind = SUPER ALT, Right, exec, ydotool mousemove -x 20 -y 0
bind = SUPER ALT, Up,    exec, ydotool mousemove -x 0 -y -20
bind = SUPER ALT, Down,  exec, ydotool mousemove -x 0 -y 20

# binde = Repeatable binds (fires multiple times while held)
binde = CTRL ALT, Left,  exec, YDOTOOL_SOCKET=$XDG_RUNTIME_DIR/.ydotool_socket ydotool mousemove -x -20 -y 0
binde = CTRL ALT, Right, exec, YDOTOOL_SOCKET=$XDG_RUNTIME_DIR/.ydotool_socket ydotool mousemove -x 20 -y 0
binde = CTRL ALT, Up,    exec, YDOTOOL_SOCKET=$XDG_RUNTIME_DIR/.ydotool_socket ydotool mousemove -x 0 -y -20
binde = CTRL ALT, Down,  exec, YDOTOOL_SOCKET=$XDG_RUNTIME_DIR/.ydotool_socket ydotool mousemove -x 0 -y 20

# Clicks (mapped to Enter and Shift)
bind = SUPER ALT, Return, exec, YDOTOOL_SOCKET=$XDG_RUNTIME_DIR/.ydotool_socket ydotool click 0xC0  # Left Click
bind = SUPER ALT, Shift_R, exec, YDOTOOL_SOCKET=$XDG_RUNTIME_DIR/.ydotool_socket ydotool click 0xC1 # Right Click
bind = SUPER ALT, Menu, exec, YDOTOOL_SOCKET=$XDG_RUNTIME_DIR/.ydotool_socket ydotool click 0xC2    # Middle Click
