# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Move/Resize active window (Left, Right, Up, Down)
bind = $mainMod $shiftMod, left, movewindow, l
bind = $mainMod $shiftMod, right, movewindow, r
bind = $mainMod $shiftMod, up, movewindow, u
bind = $mainMod $shiftMod, down, movewindow, d
bind = $mainMod $ctrlMod, left,  resizeactive, -20 0
bind = $mainMod $ctrlMod, right, resizeactive, 20 0
bind = $mainMod $ctrlMod, up,    resizeactive, 0 -20
bind = $mainMod $ctrlMod, down,  resizeactive, 0 20
