# Example special workspace (scratchpad)
# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod $shiftMod, 1, movetoworkspace, 1
bind = $mainMod $shiftMod, 2, movetoworkspace, 2
bind = $mainMod $shiftMod, 3, movetoworkspace, 3
bind = $mainMod $shiftMod, 4, movetoworkspace, 4
bind = $mainMod $shiftMod, 5, movetoworkspace, 5
bind = $mainMod $shiftMod, 6, movetoworkspace, 6
bind = $mainMod $shiftMod, 7, movetoworkspace, 7
bind = $mainMod $shiftMod, 8, movetoworkspace, 8
bind = $mainMod $shiftMod, 9, movetoworkspace, 9
bind = $mainMod $shiftMod, 0, movetoworkspace, 10
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod $shiftMod, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Cycle next/previous workspace
bind = $mainMod $altMod, right, workspace, e+1
bind = $mainMod $altMod, left, workspace, e-1

# Additional workspaces
bind = $mainMod, N, exec, ~/.config/hypr/scripts/new_workspace.sh
bind = $mainMod $shiftMod, N, exec, ~/.config/hypr/scripts/new_workspace_and_move.sh

