-- Machine class: laptop.
-- Selected by local.lua (machine = "laptop"), generated by install.sh.
--
-- Adds what a desktop does not have: touchpad, backlight, lid switch.

---------------
---- INPUT ----
---------------

hl.config({
    input = {
        touchpad = {
            natural_scroll       = true,
            disable_while_typing = true,
            tap_to_click         = true,
            clickfinger_behavior = true,
            drag_lock            = true,
            scroll_factor        = 0.5,
        },
    },
})

------------------
---- GESTURES ----
------------------

-- Three-finger horizontal swipe cycles workspaces.
hl.gesture({
    fingers   = 3,
    direction = "horizontal",
    action    = "workspace",
})

-------------------
---- BACKLIGHT ----
-------------------

-- Requires brightnessctl. -e4 -n2 gives a perceptually even ramp that never
-- hits a fully black panel.
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

-- Keyboard backlight, where the machine has one.
hl.bind("XF86KbdBrightnessUp",   hl.dsp.exec_cmd("brightnessctl -d '*::kbd_backlight' set 10%+"), { locked = true, repeating = true })
hl.bind("XF86KbdBrightnessDown", hl.dsp.exec_cmd("brightnessctl -d '*::kbd_backlight' set 10%-"), { locked = true, repeating = true })

--------------------
---- LID SWITCH ----
--------------------

-- Lock on close, wake the panel on open.
--
-- Gated through idle-guard.sh so that closing the lid while plugged in does
-- NOT lock — matching the "never lock on mains power" rule in
-- hypridle-laptop.conf. SECURITY NOTE: on AC this leaves an unlocked session
-- behind a closed lid. Drop the idle-guard.sh prefix to always lock on close.
hl.bind("switch:on:Lid Switch",
    hl.dsp.exec_cmd("~/.config/hypr/scripts/idle-guard.sh loginctl lock-session"),
    { locked = true })
hl.bind("switch:off:Lid Switch",
    hl.dsp.exec_cmd("hyprctl dispatch dpms on"),
    { locked = true })
