-- Machine class: desktop PC.
-- Selected by local.lua (machine = "pc"), generated by install.sh.
--
-- Assumptions: mains power, no lid, no touchpad, no backlight.

local mainMod = "SUPER"

-----------------
---- DEVICES ----
-----------------

hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})

-- ydotool's virtual pointer: raw input, no acceleration curve, so
-- keyboard-driven mouse movement lands where the numbers say it should.
hl.device({
    name          = "ydotoold-virtual-device",
    accel_profile = "flat",
    sensitivity   = 0,
})

-- Keyboard-driven mouse control (ydotool). Desktop only — on a laptop the
-- touchpad covers this and the binds just eat CTRL+ALT+arrows.
require("modules.mouse-bindings")

----------------------
---- POWER / IDLE ----
----------------------

-- No backlight on a desktop monitor, so brightness keys are not bound here.
-- Screen blanking is left to hypridle.conf.

-- Lock manually; a desktop does not auto-suspend.
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.exec_cmd("hyprlock"))
